"""
calc_metrics.py
Reads the raw .npz trial files generated by the UHRC benchmark, computes 
advanced control metrics (Success Rate, RMSE, IAE, ITAE, PLR) for each trial, and 
outputs categorical averages by scenario.

Usage:
  python calc_metrics.py --dir benchmark_results/trials
  python calc_metrics.py --dir benchmark_results_dynamic/trials 
  #NOTE: for dynamic obstacle trials, the figures oresented in the report was under scenario dyn_random_pop
"""

import os
import glob
import argparse
import numpy as np
from collections import defaultdict

_TC_IDS = {
    "open_field":      "TC-01", "sparse":         "TC-02",
    "moderate":        "TC-03", "dense":          "TC-04",
    "narrow_corridor": "TC-05", "gap_navigation": "TC-06",
    "cluttered":       "TC-07", "close_range":    "TC-08",
    "long_range":      "TC-09", "urban_mixed":    "TC-10",
    "urban_dense":     "TC-11", "urban_corridor": "TC-12",
}

DT = 0.01  # Integration timestep used in simulation

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--dir", type=str, default="benchmark_results/trials", 
                   help="Directory containing the .npz trial files")
    return p.parse_args()

def main():
    args = parse_args()
    
    if not os.path.exists(args.dir):
        print(f"❌ Error: Directory '{args.dir}' not found.")
        return

    npz_files = glob.glob(os.path.join(args.dir, "*.npz"))
    if not npz_files:
        print(f"❌ Error: No .npz files found in {args.dir}")
        return

    metrics = defaultdict(lambda: defaultdict(list))

    print(f"📂 Processing {len(npz_files)} raw trial files from {args.dir}...\n")

    for fpath in npz_files:
        # Extract scenario name from filename (e.g., "open_field_trial000.npz")
        basename = os.path.basename(fpath)
        scenario = basename.rsplit("_trial", 1)[0]
        
        try:
            # Load the raw arrays saved during the trial
            data = np.load(fpath)
            dists   = data["dist_log"]
            traj    = data["trajectory"]
            start   = data["start"]
            goal    = data["goal"]
            success = data["success"][0]  # Extract the boolean success flag
            
            # 1. Compute Time Array
            time_arr = np.arange(len(dists)) * DT
            
            # 2. Control Errors (RMSE, IAE, ITAE)
            rmse = np.sqrt(np.mean(dists**2))
            iae  = np.sum(np.abs(dists)) * DT
            itae = np.sum(time_arr * np.abs(dists)) * DT
            
            # 3. Path Length Ratio (PLR)
            # Actual distance traveled in XY
            path_len = np.sum(np.linalg.norm(np.diff(traj[:, :2], axis=0), axis=1))
            # Shortest possible distance from Start to Goal
            goal_dist_init = np.linalg.norm(goal[:2] - start[:2])
            plr = (path_len / goal_dist_init) if goal_dist_init > 1e-3 else 1.0

            # Store metrics
            metrics[scenario]["rmse"].append(rmse)
            metrics[scenario]["iae"].append(iae)
            metrics[scenario]["itae"].append(itae)
            metrics[scenario]["plr"].append(plr)
            metrics[scenario]["success"].append(success)
            
        except Exception as e:
            print(f"⚠️ Error reading {basename}: {e}")

    # Print Formatted Table
    col_w = [8, 18, 9, 14, 12, 12, 10]
    hdr   = ["TC-ID", "Scenario", "Succ(%)", "Avg RMSE (m)", "Avg IAE", "Avg ITAE", "Avg PLR"]
    sep   = "─" * (sum(col_w) + 3*len(col_w))
    
    print(sep)
    print(" 📈 ADVANCED TRACKING METRICS (Averaged across trials)")
    print(sep)
    print("  " + "  ".join(h.ljust(w) for h,w in zip(hdr, col_w)))
    print(sep)

    # Sort scenarios based on TC_IDS keys to maintain logical order
    sorted_scenarios = sorted(metrics.keys(), key=lambda x: list(_TC_IDS.keys()).index(x) if x in _TC_IDS else 99)

    for scenario in sorted_scenarios:
        data = metrics[scenario]
        tc = _TC_IDS.get(scenario, "TC-??")
        
        avg_succ = np.mean(data["success"]) * 100.0
        avg_rmse = np.mean(data["rmse"])
        avg_iae  = np.mean(data["iae"])
        avg_itae = np.mean(data["itae"])
        avg_plr  = np.mean(data["plr"])

        row = [
            tc, 
            scenario, 
            f"{avg_succ:.1f}",
            f"{avg_rmse:.3f}", 
            f"{avg_iae:.3f}", 
            f"{avg_itae:.3f}",
            f"{avg_plr:.3f}"
        ]
        
        print("  " + "  ".join(v.ljust(w) for v,w in zip(row, col_w)))
    print(sep)

if __name__ == "__main__":
    main()